version: '3'

services:
  db:
    container_name: archive-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=odaw
      - MYSQL_USER=odaw
      - MYSQL_PASSWORD=odaw
      - MYSQL_DATABASE=projeto_odaw
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql:rw
  
  web:
    container_name: archive-web
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/home/node/app
    links:
      - db
  
